# Generated by Django 4.1.5 on 2023-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cricao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('nome_peca', models.CharField(max_length=99)),
                ('preco_peca', models.DecimalField(decimal_places=2, max_digits=9)),
                ('categoria_peca', models.CharField(blank=True, choices=[('FN', 'Telas'), ('CB', 'Conectores'), ('CL', 'Botoes'), ('IP', 'Carcaças'), ('CR', 'Baterias'), ('FT', 'Placas'), ('DV', 'Sub-placas'), ('CM', 'Cameras'), ('FL', 'Flex'), ('AT', 'Auto-falantes'), ('LT', 'Lentes'), ('TP', 'Tampas'), ('OT', 'Outros')], max_length=2, null=True)),
                ('quantidade', models.IntegerField()),
                ('codigo_de_barras', models.IntegerField(blank=True, null=True)),
                ('preco_de_custo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fornecedor', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
    ]
