# Generated by Django 4.1 on 2022-08-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=99)),
                ('preco_peca', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
