# Generated by Django 4.1.5 on 2023-01-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecas',
            name='dia_vencimento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pecas',
            name='qtd_parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pecas',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
