# Generated by Django 4.1.5 on 2023-01-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecas',
            old_name='data_cricao',
            new_name='data_criacao',
        ),
    ]
