# Generated by Django 4.1.5 on 2023-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0002_pecas_dia_vencimento_pecas_qtd_parcela_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecas',
            name='dia_vencimento',
        ),
        migrations.AddField(
            model_name='pecas',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
