# Generated by Django 4.2.27 on 2026-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0003_remove_pecas_dia_vencimento_pecas_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecas',
            name='margem_de_lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
