# Generated by Django 4.1.1 on 2023-05-29 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colaborador', '0001_initial'),
        ('peca', '0003_remove_pecas_dia_vencimento_pecas_data_vencimento'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=90)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Em analise', 'Em analise'), ('Passar orçamento', 'Passar orçamento'), ('Aguardando liberaçāo', 'Aguardando liberaçāo'), ('Liberado', 'Liberado'), ('Em reparo', 'Em reparo'), ('Finalizado', 'Finalizado'), ('Finalizado e entregue', 'Finalizado e entregue'), ('Garantia encerrada', 'Garantia encerrada'), ('Retorno garantia', 'Retorno garantia'), ('Cancelado', 'Cancelado'), ('Cancelado e entregue', 'Cancelado e entregue')], max_length=21)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('forma_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Cartāo de credito', 'Cartāo de credito'), ('Cartāo de debito', 'Cartāo de debito'), ('Dinheiro', 'Dinheiro'), ('Fiado a receber', 'Fiado a receber')], default='Pix', max_length=21)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('qtd_parcela', models.IntegerField(blank=True, null=True)),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.colaborador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ItemsOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_orcamento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_items', to='orcamento.orcamento')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.pecas')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.servico')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
