# Generated by Django 4.1.5 on 2023-01-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0002_colaborador_observacao'),
        ('cliente', '0003_cliente_observacao'),
        ('peca', '0001_initial'),
        ('servico', '0003_rename_nome_servico_servico_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=90)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Em analise', 'Em analise'), ('Passar orçamento', 'Passar orçamento'), ('Aguardando liberaçāo', 'Aguardando liberaçāo'), ('Liberado', 'Liberado'), ('Em reparo', 'Em reparo'), ('Finalizado', 'Finalizado'), ('Finalizado e entregue', 'Finalizado e entregue'), ('Garantia encerrada', 'Garantia encerrada'), ('Retorno garantia', 'Retorno garantia'), ('Cancelado', 'Cancelado'), ('Cancelado e entregue', 'Cancelado e entregue')], max_length=21)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('forma_pagamento', models.CharField(choices=[('PX', 'Pix'), ('CC', 'Cartāo de credito'), ('CD', 'Cartāo de debito'), ('DN', 'Dinheiro'), ('FD', 'Fiado')], default='PX', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.colaborador')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ItemsOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_orcamento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_items', to='orcamento.orcamento')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.pecas')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
