# Generated by Django 4.1.1 on 2022-09-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.CharField(max_length=7, unique=True, verbose_name='nota fiscal')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ItemsOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_orcamento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantidade', models.IntegerField()),
                ('nome_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.pecas')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamento.orcamento')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
