# Generated by Django 4.1.1 on 2022-09-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0001_initial'),
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ('-pk',)},
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='nome_orcamento',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='preco_orcamento',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='quantidade',
        ),
        migrations.CreateModel(
            name='ItemsOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_orcamento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantidade', models.IntegerField()),
                ('nome_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.pecas')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamento.orcamento')),
            ],
        ),
    ]
