# Generated by Django 4.1.5 on 2023-01-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Cartāo de credito', 'Cartāo de credito'), ('Cartāo de debito', 'Cartāo de debito'), ('Dinheiro', 'Dinheiro'), ('Fiado a receber', 'Fiado a receber')], default='Pix', max_length=21),
        ),
    ]
