# Generated by Django 4.1.5 on 2023-01-17 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orcamento', '0001_initial'),
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsorcamento',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.pecas'),
        ),
    ]
