# Generated by Django 4.1.5 on 2023-01-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servico', '0003_rename_nome_servico_servico_servico'),
        ('orcamento', '0001_initial'),
        ('peca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsorcamento',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peca.pecas'),
        ),
        migrations.AddField(
            model_name='itemsorcamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
        ),
    ]
