# Generated by Django 4.1.1 on 2022-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='nf',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='nota fiscal'),
        ),
    ]
