# Generated by Django 4.2.18 on 2025-12-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peca', '0003_remove_pecas_dia_vencimento_pecas_data_vencimento'),
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsorcamento',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peca.pecas'),
        ),
    ]
