# Generated by Django 4.1 on 2023-01-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='celular',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
    ]
