# Generated by Django 4.1.1 on 2022-09-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_alter_orcamento_nf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsorcamento',
            options={},
        ),
        migrations.RemoveField(
            model_name='itemsorcamento',
            name='orcamento',
        ),
    ]
