# Generated by Django 4.1.5 on 2023-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_orcamento_data_vencimento_orcamento_qtd_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
