# Generated by Django 4.2.27 on 2026-06-09 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0003_cardmachine_cardmachinefee_and_more'),
        ('orcamento', '0002_alter_itemsorcamento_peca'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='card_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='card_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='card_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='card_final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='card_installments',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='card_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.cardmachine'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='card_payment_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pass_card_fee_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrcamentoSubmissionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('finalidade', models.CharField(max_length=40)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'finalidade', 'usado_em'], name='orcamento_o_usuario_804f67_idx')],
            },
        ),
    ]
