# Generated by Django 4.1.1 on 2022-09-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0003_alter_itemsorcamento_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orcamento',
        ),
    ]
