# Generated by Django 4.1.1 on 2022-09-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0005_orcamento_itemsorcamento_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsorcamento',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_items', to='orcamento.orcamento'),
        ),
    ]
