# Generated by Django 4.2.18 on 2025-12-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credito_1x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_2x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_3x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_4x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_5x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_6x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_7x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_8x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_9x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_10x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_11x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credito_12x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
