# Generated by Django 4.1.5 on 2023-01-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='forma_pagamento',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Cartāo de credito', 'Cartāo de credito'), ('Cartāo de debito', 'Cartāo de debito'), ('Dinheiro', 'Dinheiro'), ('Fiado', 'Fiado')], default='Pix', max_length=20),
        ),
    ]
