# Generated by Django 4.1.5 on 2023-03-31 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_categoria_produtos'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
    ]
