# Generated by Django 3.2.13 on 2022-08-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterField(
            model_name='itemsvenda',
            name='vendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venda.vendas', verbose_name='vendas'),
        ),
    ]
