# Generated by Django 4.1.1 on 2025-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_itemsvenda_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
