# Generated by Django 4.1 on 2023-01-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_rename_preco_itemsvenda_preco_de_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsvenda',
            old_name='preco_de_venda',
            new_name='preco',
        ),
    ]
