# Generated by Django 4.1.1 on 2025-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_vendas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
