# Generated by Django 4.1.1 on 2025-12-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_alter_vendas_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='data',
        ),
    ]
