# Generated by Django 4.1.1 on 2025-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0007_remove_vendas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
