# Generated by Django 4.1.1 on 2025-12-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_vendas_lucro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='lucro',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='valor_total',
        ),
    ]
