# Generated by Django 4.2.27 on 2025-12-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0010_remove_vendas_lucro_remove_vendas_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='total_bruto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendas',
            name='total_liquido',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
