# Generated by Django 4.2.18 on 2025-12-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0011_vendas_total_bruto_vendas_total_liquido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='total_bruto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='total_liquido',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
