# Generated by Codex on 2026-06-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_categoria_produto'),
        ('venda', '0013_vendas_card_base_amount_vendas_card_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto'),
        ),
    ]
