# Generated by Django 4.1.5 on 2023-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanhouseservico',
            name='descricao_servico',
            field=models.CharField(choices=[('Impressāo comum', 'Impressao comum'), ('Impressāo colorida', 'Impressāo colorida'), ('Copia colorida', 'Copia colorida'), ('Copia comum', 'Copia comum'), ('Curriculo', 'Curriculo'), ('Emplastificao', 'Emplastificao'), ('2ºvia boleto', '2ºvia boleto'), ('Certidao negativa', 'Certidao negativa'), ('Agendamentos', 'Agendamentos'), ('Digitalizacao', 'Digitalizacao'), ('Digitacao documento', 'Digitacao documento'), ('Outros servicos', 'Outros servicos')], max_length=20),
        ),
    ]
