# Generated by Django 4.1.5 on 2023-03-15 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lanhouse', '0002_alter_lanhouseservico_descricao_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanhouseServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('servico', models.CharField(max_length=90)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=9)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='itemslanhouse',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lanhouse.lanhouseservicos'),
        ),
        migrations.DeleteModel(
            name='LanhouseServico',
        ),
    ]
