# Generated by Django 4.1.5 on 2023-03-15 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lanhouse', '0003_lanhouseservicos_alter_itemslanhouse_servico_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanhouseServicos',
            new_name='LanhouseServico',
        ),
    ]
