# Generated by Django 4.1.5 on 2023-03-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanhouse', '0004_rename_lanhouseservicos_lanhouseservico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lanhouseservico',
            old_name='preco_venda',
            new_name='preco',
        ),
    ]
