# Generated by Django 4.2.18 on 2026-06-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lanhouse', '0005_rename_preco_venda_lanhouseservico_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanhouseSubmissionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('finalidade', models.CharField(max_length=40)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemslanhouse',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lanhouse.lanhouseservico'),
        ),
        migrations.AddConstraint(
            model_name='lanhouseservico',
            constraint=models.UniqueConstraint(fields=('usuario', 'servico'), name='unique_lanhouse_servico_por_usuario'),
        ),
        migrations.AddField(
            model_name='lanhousesubmissiontoken',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lanhousesubmissiontoken',
            index=models.Index(fields=['usuario', 'finalidade', 'usado_em'], name='lanhouse_la_usuario_caf7f7_idx'),
        ),
    ]
