# Generated by Django 4.2.27 on 2026-06-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_cardmachine_cardmachinefee_and_more'),
        ('lanhouse', '0006_lanhousesubmissiontoken_alter_itemslanhouse_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanhousemodel',
            name='card_base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lanhousemodel',
            name='card_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lanhousemodel',
            name='card_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lanhousemodel',
            name='card_final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lanhousemodel',
            name='card_installments',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lanhousemodel',
            name='card_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.cardmachine'),
        ),
        migrations.AddField(
            model_name='lanhousemodel',
            name='card_payment_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lanhousemodel',
            name='pass_card_fee_to_customer',
            field=models.BooleanField(default=False),
        ),
    ]
