# Generated by Django 4.2.27 on 2026-06-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanhouse', '0007_lanhousemodel_card_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanhouseservico',
            name='margem_de_lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
