# Generated by Django 4.1.5 on 2023-01-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_fornecedores_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
