# Generated by Django 4.1.1 on 2023-01-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_edicao', models.DateField(auto_now=True)),
                ('nome_cliente', models.CharField(max_length=90)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone_contato', models.CharField(max_length=15)),
                ('telefone_contato_2', models.CharField(blank=True, max_length=15, null=True)),
                ('rua', models.CharField(blank=True, max_length=99, null=True)),
                ('numero_casa', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
    ]
