# Generated by Django 4.1 on 2022-09-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
