# Generated by Django 4.1.5 on 2023-01-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria_despesa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_despesa', models.CharField(max_length=90)),
                ('preco_despesa', models.DecimalField(decimal_places=2, max_digits=9)),
                ('observacao', models.TextField(blank=True, max_length=1000, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Pix', 'Pix'), ('Cartāo de credito', 'Cartāo de credito'), ('Cartāo de debito', 'Cartāo de debito'), ('Dinheiro', 'Dinheiro'), ('Fiado a pagar', 'Fiado')], max_length=17, null=True)),
                ('categoria_despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='despesa.categoriadespesa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
