# Generated by Django 4.1.1 on 2022-09-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_despesa', models.CharField(max_length=90)),
                ('preco_despesa', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
