# Generated by Django 4.1.5 on 2023-01-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Pago', 'Pago'), ('A pagar', 'A pagar')], max_length=16, null=True),
        ),
    ]
