# Generated by Django 4.1 on 2023-01-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria_despesa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria_despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='despesa.categoriadespesa'),
        ),
    ]
