# Generated by Django 4.1 on 2023-02-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0002_alter_despesa_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='qtd_parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
