# Generated by Django 4.1.5 on 2023-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0002_despesa_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='status',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('Pix', 'Pix'), ('Cartāo de credito', 'Cartāo de credito'), ('Cartāo de debito', 'Cartāo de debito'), ('Dinheiro', 'Dinheiro'), ('Fiado', 'Fiado')], max_length=17, null=True),
        ),
    ]
