# Generated by Django 4.2.27 on 2026-06-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanhouse', '0007_lanhousemodel_card_base_amount_and_more'),
        ('despesa', '0004_alter_despesa_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='lanhouse_card_fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_taxa_maquininha', to='lanhouse.lanhousemodel'),
        ),
    ]
