# Generated by Django 4.2.27 on 2026-06-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_alter_itemsorcamento_peca'),
        ('venda', '0012_remove_vendas_total_bruto_and_more'),
        ('despesa', '0005_despesa_lanhouse_card_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='orcamento_card_fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_taxa_maquininha', to='orcamento.orcamento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='venda_card_fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesa_taxa_maquininha', to='venda.vendas'),
        ),
    ]
