# Generated by Django 4.2.27 on 2026-06-13 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0006_despesa_orcamento_card_fee_despesa_venda_card_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='despesa_fixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despesa',
            name='dia_vencimento_fixo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
