# Generated by Django 4.2.18 on 2026-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0007_despesa_despesa_fixa_despesa_dia_vencimento_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('despesa_empresa', 'Empresa'), ('prolabore', 'Pró-labore')], default='despesa_empresa', max_length=20),
        ),
    ]
