# Generated by Django 4.2.18 on 2026-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0008_despesa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='fiado_pago',
            field=models.BooleanField(default=False),
        ),
    ]
