# Generated by Django 4.2.18 on 2026-06-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0009_despesa_fiado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('despesa_empresa', 'Empresa'), ('prolabore', 'Pró-labore'), ('divida', 'Dívida')], default='despesa_empresa', max_length=20),
        ),
    ]
