# Generated by Django 4.2.18 on 2026-06-13 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0010_alter_despesa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='dia_vencimento_parcela',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
