# Generated by Django 4.1.5 on 2023-01-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_remove_servico_preco_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome_servico',
            new_name='servico',
        ),
    ]
