# Generated by Django 4.1.5 on 2023-01-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('nome_produto', models.CharField(max_length=99)),
                ('categoria_produtos', models.CharField(blank=True, choices=[('FN', 'Fones'), ('CB', 'Cabos'), ('CP', 'Capas'), ('PL', 'Peliculas'), ('AD', 'Adaptadores'), ('CL', 'Celulares'), ('IP', 'iPhones'), ('CR', 'Carregadores'), ('FT', 'Fontes'), ('DV', 'Diversos'), ('IN', 'Informatica')], max_length=2, null=True)),
                ('quantidade', models.IntegerField()),
                ('codigo_de_barras', models.IntegerField(blank=True, null=True)),
                ('preco_de_custo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('forma_pagamento', models.CharField(choices=[('Cartāo de credito', 'Pix'), ('Cartāo de credito', 'Cartāo de credito'), ('Cartāo de debito', 'Cartāo de debito'), ('Dinheiro', 'Dinheiro'), ('Fiado a pagar', 'Fiado a pagar')], default='Cartāo de credito', max_length=21)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
