# Generated by Django 3.2.13 on 2022-06-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=99)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.PositiveIntegerField()),
            ],
        ),
    ]
