# Generated by Django 4.1.5 on 2023-01-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria_produtos',
            field=models.CharField(blank=True, choices=[('FN', 'Fones'), ('CB', 'Cabos'), ('CP', 'Capas'), ('PL', 'Peliculas'), ('AD', 'Adaptadores'), ('CL', 'Celulares'), ('IP', 'iPhones'), ('CR', 'Carregadores'), ('FT', 'Fontes'), ('DV', 'Diversos'), ('IN', 'Informatica'), ('CS', 'Caixa de som')], max_length=2, null=True),
        ),
    ]
