# Generated by Django 4.1.5 on 2023-03-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria_produtos',
            field=models.CharField(blank=True, choices=[('Fones', 'Fones'), ('Cabos', 'Cabos'), ('Capas', 'Capas'), ('Peliculas', 'Peliculas'), ('Adaptadores', 'Adaptadores'), ('Celulares', 'Celulares'), ('iPhones', 'iPhones'), ('Carregadores', 'Carregadores'), ('Fontes', 'Fontes'), ('Diversos', 'Diversos'), ('Informatica', 'Informatica'), ('Caixa de som', 'Caixa de som')], max_length=20, null=True),
        ),
    ]
