# Generated by Django 4.1 on 2023-01-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_de_venda',
            new_name='preco',
        ),
    ]
