# Generated by Django 4.2.18 on 2025-02-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_categoria_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria_produtos',
            field=models.CharField(blank=True, choices=[('Fones', 'Fones'), 
                                                        ('Cabos', 'Cabos'), 
                                                        ('Capas', 'Capas'), 
                                                        ('Peliculas', 'Peliculas'),
                                                        ('Adaptadores', 'Adaptadores'), 
                                                        ('Celulares', 'Celulares'), 
                                                        ('iPhones', 'iPhones'), 
                                                        ('Carregadores', 'Carregadores'), 
                                                        ('Fontes', 'Fontes'), ('Diversos', 'Diversos'), 
                                                        ('Informatica', 'Informatica'), 
                                                        ('Caixa de som', 'Caixa de som'), 
                                                        ('Copos | Garrafas', 'Copos | Garrafas')], 
                                                        max_length=20, null=True),
        ),
    ]
