# Generated by Django 4.1 on 2023-01-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_preco_de_venda_produto_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_de_venda',
        ),
    ]
