# Generated by Django 4.2.18 on 2025-02-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_categoria_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='margem_de_lucro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
