# Generated by Django 4.1 on 2023-01-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_rename_preco_de_venda_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria_produtos',
            field=models.CharField(choices=[('FN', 'Fones'), ('CB', 'Cabos'), ('CL', 'Celulares'), ('IP', 'iPhones'), ('CR', 'Carregadores'), ('FT', 'Fontes'), ('DV', 'Diversos')], max_length=2),
        ),
    ]
