# Generated by Django 4.2.18 on 2025-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_margem_de_lucro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='margem_de_lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
