# Generated by Django 4.2.18 on 2025-02-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_margem_de_lucro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='forma_pagamento',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Cartāo de credito', 'Cartāo de credito'), ('Cartāo de debito', 'Cartāo de debito'), ('Dinheiro', 'Dinheiro'), ('Fiado a pagar', 'Fiado a pagar')], default='Pix', max_length=21),
        ),
    ]
