# Generated by Codex on 2026-06-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_CATEGORIAS_PRODUTOS = [
    'Fones',
    'Cabos',
    'Capas',
    'Peliculas',
    'Adaptadores',
    'Celulares',
    'iPhones',
    'Carregadores',
    'Fontes',
    'Diversos',
    'Informatica',
    'Caixa de som',
    'Copos | Garrafas',
    'Relogios',
    'Brinquedos',
    'Perfumes',
]


def criar_categorias_padrao(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Produto = apps.get_model('produto', 'Produto')
    CategoriaProduto = apps.get_model('produto', 'CategoriaProduto')

    for user in User.objects.all():
        for nome in DEFAULT_CATEGORIAS_PRODUTOS:
            CategoriaProduto.objects.get_or_create(usuario_id=user.pk, nome=nome)

    for produto in Produto.objects.exclude(categoria_produtos__isnull=True).exclude(categoria_produtos=''):
        nome = (produto.categoria_produtos or '').strip()
        if not nome:
            continue

        categoria, _created = CategoriaProduto.objects.get_or_create(
            usuario_id=produto.usuario_id,
            nome=nome,
        )
        produto.categoria_id = categoria.pk
        produto.categoria_produtos = categoria.nome
        produto.save(update_fields=['categoria', 'categoria_produtos'])


def remover_vinculo_categoria(apps, schema_editor):
    Produto = apps.get_model('produto', 'Produto')
    Produto.objects.update(categoria_id=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0007_alter_produto_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome',),
                'constraints': [
                    models.UniqueConstraint(fields=('usuario', 'nome'), name='unique_categoria_produto_por_usuario'),
                ],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.categoriaproduto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria_produtos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(criar_categorias_padrao, remover_vinculo_categoria),
    ]
