# Generated by Django 4.1.5 on 2023-01-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_cliente_data_criacao_alter_cliente_data_edicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contas_a_receber', models.CharField(max_length=90)),
                ('preco_contas_a_receber', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=models.SET('Cliente excluido'), to='cliente.cliente')),
            ],
        ),
    ]
