# Generated by Django 4.1.5 on 2023-03-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasareceber',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contasareceber',
            name='qtd_parcela',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contasareceber',
            name='status',
            field=models.CharField(choices=[('Pago', 'Pago'), ('A receber', 'A receber'), ('Calote', 'Calote')], default='A receber', max_length=20),
        ),
        migrations.AddField(
            model_name='contasareceber',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
