# Generated by Django 4.1.5 on 2023-01-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_contasareceber_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasareceber',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
