# Generated by Django 4.2.27 on 2026-06-09 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0002_contasareceber_data_vencimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CardMachineFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('debit', 'Débito'), ('credit', 'Crédito')], max_length=10)),
                ('installments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='financeiro.cardmachine')),
            ],
            options={
                'ordering': ('card_machine__name', 'payment_type', 'installments'),
            },
        ),
        migrations.AddConstraint(
            model_name='cardmachinefee',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_type', 'debit')), fields=('card_machine', 'payment_type'), name='unique_debit_fee_por_maquininha'),
        ),
        migrations.AddConstraint(
            model_name='cardmachinefee',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_type', 'credit')), fields=('card_machine', 'payment_type', 'installments'), name='unique_credit_fee_parcela_por_maquininha'),
        ),
        migrations.AddConstraint(
            model_name='cardmachine',
            constraint=models.UniqueConstraint(fields=('usuario', 'name'), name='unique_card_machine_por_usuario'),
        ),
    ]
