# Generated by Codex on 2026-06-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("despesa", "0006_despesa_orcamento_card_fee_despesa_venda_card_fee"),
        ("financeiro", "0003_cardmachine_cardmachinefee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaLancamentoFinanceiro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(choices=[("income", "Receita"), ("expense", "Despesa")], default="income", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("income", "Receita"), ("expense", "Despesa")], default="income", max_length=10)),
                ("descricao", models.CharField(max_length=160)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_lancamento", models.DateField(default=django.utils.timezone.localdate)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="financeiro.categorialancamentofinanceiro")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-data_lancamento", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="FechamentoCaixa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField()),
                ("saldo_abertura", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_receitas", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_despesas", models.DecimalField(decimal_places=2, max_digits=10)),
                ("saldo_esperado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_contado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("diferenca", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(choices=[("balanced", "Balanceado"), ("cash_over", "Sobra de Caixa"), ("cash_shortage", "Falta de Caixa")], default="balanced", max_length=20)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("despesa_falta", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fechamentos_falta", to="despesa.despesa")),
                ("lancamento_sobra", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fechamentos_sobra", to="financeiro.lancamentofinanceiro")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fechamentos_caixa", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-data", "-created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="categorialancamentofinanceiro",
            constraint=models.UniqueConstraint(fields=("usuario", "nome", "tipo"), name="unique_categoria_lancamento_financeiro_usuario"),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(fields=("usuario", "tipo", "data_lancamento"), name="financeiro__usuario_f58fba_idx"),
        ),
        migrations.AddIndex(
            model_name="fechamentocaixa",
            index=models.Index(fields=("usuario", "data"), name="financeiro__usuario_7faedb_idx"),
        ),
        migrations.AddIndex(
            model_name="fechamentocaixa",
            index=models.Index(fields=("usuario", "status", "data"), name="financeiro__usuario_5291a2_idx"),
        ),
    ]
